# Generated by Django 5.0.1 on 2024-11-25 11:08

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "model_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "model_modified_at",
                    apps.common.models.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("summary", models.TextField(default="")),
                ("company", models.CharField(blank=True, max_length=64, null=True)),
                ("location", models.CharField(blank=True, max_length=64, null=True)),
                ("email", models.CharField(blank=True, max_length=64, null=True)),
                ("phone", models.CharField(blank=True, max_length=32, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=256, null=True)),
                ("github", models.CharField(blank=True, max_length=256, null=True)),
                ("website", models.CharField(blank=True, max_length=256, null=True)),
                ("skills", models.JSONField(default=list)),
                ("languages", models.JSONField(default=list)),
                ("hobbies", models.JSONField(default=list)),
                ("interests", models.JSONField(default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["model_created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "model_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "model_modified_at",
                    apps.common.models.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("role", models.CharField(max_length=128)),
                ("location", models.CharField(max_length=128)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FLT", "Full-time"),
                            ("PRT", "Part-time"),
                            ("SLE", "Self-employed"),
                            ("VOL", "Volunteer"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FLT", "Full-time"),
                            ("PRT", "Part-time"),
                            ("SLE", "Self-employed"),
                            ("VOL", "Volunteer"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=256, null=True)),
                ("starting", models.DateField(blank=True, null=True)),
                ("ending", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.profile"
                    ),
                ),
            ],
            options={
                "ordering": ["model_created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tailor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "model_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "model_modified_at",
                    apps.common.models.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("additional", models.TextField(default="")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.profile"
                    ),
                ),
            ],
            options={
                "ordering": ["model_created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CurriculumVitae",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "model_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "model_modified_at",
                    apps.common.models.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("uri", models.CharField(max_length=128)),
                ("comment", models.TextField()),
                ("content", models.JSONField()),
                ("meta", models.JSONField()),
                (
                    "tailor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.tailor"
                    ),
                ),
            ],
            options={
                "ordering": ["model_created_at"],
                "abstract": False,
            },
        ),
    ]
