# Generated by Django 5.0.1 on 2024-11-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_experience_category_alter_profile_hobbies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculumvitae",
            name="fit",
            field=models.IntegerField(
                default=0, help_text="an integer value between 0 and 5"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="comment",
            field=models.TextField(
                help_text="AI's comment about the CV and position match"
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="content",
            field=models.TextField(help_text="latex text for CV to be rendered"),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="meta",
            field=models.JSONField(
                help_text="meta information including prompt and model versions"
            ),
        ),
    ]
