# Generated by Django 5.0.1 on 2024-11-26 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_curriculumvitae_fit_alter_curriculumvitae_comment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="curriculumvitae",
            old_name="fit",
            new_name="fitness",
        ),
    ]
