# Generated by Django 5.0.1 on 2024-12-10 22:42

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_rename_fit_curriculumvitae_fitness"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculumvitae",
            name="file",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.common.models.file_upload_path
            ),
        ),
    ]
