# Generated by Django 5.0.1 on 2024-12-10 22:53

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_curriculumvitae_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curriculumvitae",
            name="uri",
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.common.models.file_upload_path
            ),
        ),
    ]
