# Generated by Django 5.0.1 on 2024-12-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_experience_category_alter_experience_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("EDU", "Education"), ("CAR", "Carrier"), ("PRJ", "Project")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FLT", "Full-time"),
                    ("PRT", "Part-time"),
                    ("SLE", "Self-employed"),
                    ("VOL", "Volunteer"),
                    ("CON", "Contract"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
